services:
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./backend/prisma:/app/prisma
    ports:
      - "8080:8080"
    restart: unless-stopped

  bot:
    build: ./backend
    command: npm run bot
    env_file:
      - .env
    volumes:
      - ./backend/prisma:/app/prisma
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    restart: unless-stopped
